## Port configuration
server:
  port: 8080

## Datasource - H2 to initial tests

spring:
  datasource:
    url: jdbc:h2:mem:supermarket
    username: root
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true